services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresql:/var/lib/postgresql/data
    networks:
      - cinema_network

  backend:
    build:
      context: ./backend-go
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - cinema_network

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /home/bun/app
    volumes:
      - ./frontend:/home/bun/app
      - /home/bun/app/node_modules
    expose:
      - "5173"
    ports:
      - "80:5173"
    restart: on-failure
    depends_on:
      - backend

volumes:
  postgresql:

networks:
  cinema_network:
    driver: bridge
