version: '3'
services:
  backend:
    image: cinema:staging
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgresdb
    networks:
      - cinema_network
  postgresdb:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cinema
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgresql2:/var/lib/postgresql/data
      - ./cinemav2.sql:/docker-entrypoint-initdb.d/cinemav2.sql
    networks:
      - cinema_network

volumes:
  postgresql2:

networks:
  cinema_network:
    driver: bridge