name: Deployment
on:
  push:
    branches:
      - master
env:
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Clone git repository or pull updates
        run: |
          if [ -d "~/.git" ]; then
            echo "Repository exists. Pulling latest changes...";
            cd ~/ && git pull;
          else
            echo "Repository does not exist. Cloning...";
            git clone https://github.com/Darkiee12/cinema-golang.git ~/;
          fi

      - name: Create .env file on droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER}}" > ~/.env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ~/.env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> ~/.env
      - name: Clone git repository
        run: git clone

      - name: Copy docker-compose.yml to droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: docker-compose.yml
          target: /root/

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~
            docker-compose down
            docker-compose up -d
            docker-compose logs
